### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rocosttaa** [gabrielbrop/haxball-server#1]
![image](https://user-images.githubusercontent.com/86488916/134327376-c0694626-cfb2-4a7f-aefc-20a631c3d6a9.png)

I've been using this server for a while and when it's time to open the room it's giving it away. Help

**Comment by rocosttaa** [comment]
Sorted out. Problem was in the syntax by mistake myself.

**Comment by rocosttaa** [comment]
I have a problem where a room opens but people can't get into it. Please help.

**Comment by gabrielbrop** [comment]
This issue was solved on Discord. Because of WebRTC's local IPs anonymization, implemented on Chrome 78 since it exposed the IP of VPN users (considered a security problem), connections to Haxball became problematic in some VPS.

A `server.disableAnonymizeLocalIps` option to the configuration file was added. This option disables the anonymization feature, [according to Haxball Headless' documentation](https://github.com/haxball/haxball-issues/wiki/Headless-Host#connectivity-warning). Version 4.1.0 has been released with the new option.

If problems persist, make sure you've got all the required ports open. Haxball Server requires the 9500 and 9501 ports to be open and free to work.

It also dinamically attaches ports to Chrome sessions. Although it automatically detects and avoids using ports being used, I recommend reserving the 9500-9520 range to Haxball Server (or 9500-9501 + the number of rooms you want to open with it. I'm pretty sure though you're not going to open more than 19 rooms, so it's safe to use 9520).
